# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jesc < Formula
  desc "DifA simple CLI tool to deeply unescape nested escaped JSON strings inside JSON objects."
  homepage "https://github.com/fardhanardhi/jesc"
  version "0.1.2"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.2/jesc_Darwin_x86_64.tar.gz"
      sha256 "a22744869b3cfe73d20a71185ee66a870a92dde1db571098936466b06c94269f"

      def install
        bin.install "jesc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.2/jesc_Darwin_arm64.tar.gz"
      sha256 "dcaae7115f6bed23fcb75ed94324e7b860e4f639f6a10998b8f24867055700b2"

      def install
        bin.install "jesc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.2/jesc_Linux_x86_64.tar.gz"
      sha256 "3a40ae5180f41bacc43595e83c9b9e0c2c3265a2c190b14c7aa50ca6d4af3ccb"
      def install
        bin.install "jesc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.2/jesc_Linux_arm64.tar.gz"
      sha256 "535563fa0ce34f307b316664b6eaeda8df767b45e622e883129dead22bb9bfc8"
      def install
        bin.install "jesc"
      end
    end
  end
end
