# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jesc < Formula
  desc "A simple CLI tool to deeply unescape nested escaped JSON strings inside JSON objects."
  homepage "https://github.com/fardhanardhi/jesc"
  version "0.1.5"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.5/jesc_Darwin_x86_64.tar.gz"
      sha256 "770d9fa74deba31d56bd485b36c491b10b5e9c45488be3038c28dd6ea6b1b9dd"

      def install
        bin.install "jesc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.5/jesc_Darwin_arm64.tar.gz"
      sha256 "99793b90bd9342a23f3a0730399d28c6801d4a7dc9560a73d2b0ed589e90df7d"

      def install
        bin.install "jesc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.5/jesc_Linux_x86_64.tar.gz"
      sha256 "661e646dc1ab09bf9b0eb466ba8847827abce36e4b6fc152d158b0800e8127ec"
      def install
        bin.install "jesc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.5/jesc_Linux_arm64.tar.gz"
      sha256 "6399695eba24b838d84091c81bd0a85f8493414bdfca13213a4c1c74f7e65534"
      def install
        bin.install "jesc"
      end
    end
  end
end
