# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jesc < Formula
  desc "A simple CLI tool to deeply unescape nested escaped JSON strings inside JSON objects."
  homepage "https://github.com/fardhanardhi/jesc"
  version "0.1.3"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.3/jesc_Darwin_x86_64.tar.gz"
      sha256 "45f45922a83208b09516e5c4935d071ecd8aadc90cb1699ac21c1e25fc5d47be"

      def install
        bin.install "jesc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.3/jesc_Darwin_arm64.tar.gz"
      sha256 "61f05ca090e2fb94015edaacd1a0b2ab19a44c787591120273dae4bdde71771d"

      def install
        bin.install "jesc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.3/jesc_Linux_x86_64.tar.gz"
      sha256 "6a6ef047f16c22076edaf4dd6b4e7d928a6bbd8a1ce42298d831e0304280293f"
      def install
        bin.install "jesc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.3/jesc_Linux_arm64.tar.gz"
      sha256 "5a26f824d9f642f8f43920841206e1356f2aba65a20fe8d06f9bb3aa1ed9d1c8"
      def install
        bin.install "jesc"
      end
    end
  end
end
